name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
target-commitish: main
categories:
  - title: "✨ Features"
    labels: ["✨ enhancement", "feat"]
  - title: "🐛 Bug fixes"
    labels: ["🐛 bug", "fix"]
  - title: "🚀 Performance"
    labels: ["perf"]
  - title: "♻️ Refactors"
    labels: ["refactor"]
  - title: "📚 Documentation"
    labels: ["docs"]
  - title: "🧹 Maintenance"
    labels: ["🧹 chore", "chore", "📦 dependencies", "🤖 ci"]

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: ["💥 breaking"]
  minor:
    labels: ["✨ enhancement", "feat"]
  patch:
    labels: ["🐛 bug", "fix", "🧹 chore", "chore", "docs", "refactor", "perf"]
  default: patch

template: |
  ## 🎉 What's new in v$RESOLVED_VERSION

  $CHANGES

  **Full changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
